services:
  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: user_service
    ports:
      - "8001:8001"
    restart: unless-stopped

  order_service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    container_name: order_service
    ports:
      - "8002:8002"
    restart: unless-stopped

  payment_service:
    build:
      context: .
      dockerfile: payment_service/Dockerfile
    container_name: payment_service
    ports:
      - "8003:8003"
    restart: unless-stopped